name: Release to GitHub
on:
    push:
        paths:
        - 'res/reference_audio/**' # Trigger on changes in the reference_audio folder

permissions:
    contents: write
    packages: write

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get latest commit info
              id: get_commit_info
              run: |
                echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
                echo "COMMIT_URL=$(git log -1 --pretty=%H)" >> $GITHUB_OUTPUT
                echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT

            - name: Generate tag name
              id: generate_tag_name
              run: |
                echo "TAG_NAME=v$(date +'%Y.%m.%d-%H.%M.%S')" >> $GITHUB_OUTPUT

            - name: Compress reference_audio folder
              run: |
                zip -r reference_audio.zip res/reference_audio

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.generate_tag_name.outputs.TAG_NAME }}
                release_name: Release ${{ steps.generate_tag_name.outputs.TAG_NAME }}
                body: |
                    最新提交: ${{ steps.get_commit_info.outputs.COMMIT_MESSAGE }}
                    链接: https://github.com/${{ github.repository }}/commit/${{ steps.get_commit_info.outputs.COMMIT_URL }}
                    作者: ${{ steps.get_commit_info.outputs.COMMIT_AUTHOR }}
                prerelease: false

            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./reference_audio.zip
                asset_name: reference_audio.zip
                asset_content_type: application/zip